<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="TUnit" Version="1.67.0" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\BergetSharp\BergetSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Files\sample-speech-1m.mp3">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Files\sample-bumblebee-400x300.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>