name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BERGET_API_KEY: ${{ secrets.BERGET_API_KEY }}
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore BergetSharp.sln

      - name: Build
        run: dotnet build BergetSharp.sln --no-restore

      - name: Test
        run: dotnet test BergetSharp.sln --no-build --logger trx
